Repository elastic/helm-charts, pull requests merged in 2020-11, with the labels that each got.

#880 [meta] add support for helm 2.17.0 and k8s 1.17
  README.md
  helpers/helm-tester/Dockerfile
  helpers/matrix.yml
  helpers/terraform/Dockerfile
Labels: meta

#882 [metricbeat] use relocated stable repo for kube-state-metrics
  metricbeat/requirements.lock
Labels: metricbeat

#885 [meta] clean deprecated helpers tools and docs
  CONTRIBUTING.md
  helpers/release.md
  helpers/release.py
Labels: meta

#890 [meta] update rbac.authorization.k8s.io api
  apm-server/templates/clusterrole.yaml
  apm-server/templates/clusterrolebinding.yaml
  filebeat/templates/clusterrole.yaml
  filebeat/templates/clusterrolebinding.yaml
  metricbeat/templates/clusterrole.yaml
  metricbeat/templates/clusterrolebinding.yaml
Labels: enhancement, helm3, meta

#891 [meta] increase helm timeout
  apm-server/examples/default/Makefile
  apm-server/examples/oss/Makefile
  apm-server/examples/security/Makefile
  elasticsearch/examples/config/Makefile
  elasticsearch/examples/default/Makefile
  elasticsearch/examples/docker-for-mac/Makefile
  elasticsearch/examples/kubernetes-kind/Makefile
  elasticsearch/examples/microk8s/Makefile
  elasticsearch/examples/migration/Makefile
  elasticsearch/examples/minikube/Makefile
  elasticsearch/examples/multi/Makefile
  elasticsearch/examples/openshift/Makefile
  elasticsearch/examples/oss/Makefile
  elasticsearch/examples/security/Makefile
  filebeat/examples/default/Makefile
  filebeat/examples/oss/Makefile
  filebeat/examples/security/Makefile
  kibana/examples/default/Makefile
  kibana/examples/openshift/Makefile
  kibana/examples/oss/Makefile
  kibana/examples/security/Makefile
  logstash/examples/default/Makefile
  logstash/examples/elasticsearch/Makefile
  logstash/examples/oss/Makefile
  logstash/examples/security/Makefile
  metricbeat/examples/default/Makefile
  metricbeat/examples/oss/Makefile
  metricbeat/examples/security/Makefile
Labels: meta

#516 Helm 3
  README.md
  apm-server/README.md
  apm-server/examples/default/Makefile
  apm-server/examples/oss/Makefile
  apm-server/examples/security/Makefile
  apm-server/templates/_helpers.tpl
  elasticsearch/README.md
  elasticsearch/examples/config/Makefile
  elasticsearch/examples/default/Makefile
  elasticsearch/examples/docker-for-mac/Makefile
  elasticsearch/examples/kubernetes-kind/Makefile
  elasticsearch/examples/microk8s/Makefile
  elasticsearch/examples/migration/Makefile
  elasticsearch/examples/minikube/Makefile
  elasticsearch/examples/multi/Makefile
  elasticsearch/examples/openshift/Makefile
  elasticsearch/examples/oss/Makefile
  elasticsearch/examples/security/Makefile
  elasticsearch/templates/NOTES.txt
  elasticsearch/templates/_helpers.tpl
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  filebeat/README.md
  filebeat/examples/default/Makefile
  filebeat/examples/oss/Makefile
  filebeat/examples/security/Makefile
  helpers/common.mk
  helpers/helm-tester/Dockerfile
  helpers/helpers.py
  helpers/terraform/Dockerfile
  helpers/terraform/Makefile
  kibana/README.md
  kibana/examples/default/Makefile
  kibana/examples/openshift/Makefile
  kibana/examples/oss/Makefile
  kibana/examples/security/Makefile
  kibana/templates/_helpers.tpl
  logstash/README.md
  logstash/examples/default/Makefile
  logstash/examples/elasticsearch/Makefile
  logstash/examples/oss/Makefile
  logstash/examples/security/Makefile
  logstash/templates/_helpers.tpl
  logstash/templates/service.yaml
  metricbeat/README.md
  metricbeat/examples/default/Makefile
  metricbeat/examples/oss/Makefile
  metricbeat/examples/security/Makefile
  metricbeat/templates/deployment.yaml
Labels: breaking change, enhancement, helm3

#902 Helm 3 (#516)
  README.md
  apm-server/README.md
  apm-server/examples/default/Makefile
  apm-server/examples/oss/Makefile
  apm-server/examples/security/Makefile
  apm-server/templates/_helpers.tpl
  elasticsearch/README.md
  elasticsearch/examples/config/Makefile
  elasticsearch/examples/default/Makefile
  elasticsearch/examples/docker-for-mac/Makefile
  elasticsearch/examples/kubernetes-kind/Makefile
  elasticsearch/examples/microk8s/Makefile
  elasticsearch/examples/migration/Makefile
  elasticsearch/examples/minikube/Makefile
  elasticsearch/examples/multi/Makefile
  elasticsearch/examples/openshift/Makefile
  elasticsearch/examples/oss/Makefile
  elasticsearch/examples/security/Makefile
  elasticsearch/examples/upgrade/Makefile
  elasticsearch/examples/upgrade/scripts/upgrade.sh
  elasticsearch/templates/NOTES.txt
  elasticsearch/templates/_helpers.tpl
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  filebeat/README.md
  filebeat/examples/default/Makefile
  filebeat/examples/oss/Makefile
  filebeat/examples/security/Makefile
  helpers/common.mk
  helpers/helm-tester/Dockerfile
  helpers/helpers.py
  helpers/terraform/Dockerfile
  helpers/terraform/Makefile
  kibana/README.md
  kibana/examples/default/Makefile
  kibana/examples/openshift/Makefile
  kibana/examples/oss/Makefile
  kibana/examples/security/Makefile
  kibana/templates/_helpers.tpl
  logstash/README.md
  logstash/examples/default/Makefile
  logstash/examples/elasticsearch/Makefile
  logstash/examples/oss/Makefile
  logstash/examples/security/Makefile
  logstash/templates/_helpers.tpl
  logstash/templates/service.yaml
  metricbeat/README.md
  metricbeat/examples/default/Makefile
  metricbeat/examples/oss/Makefile
  metricbeat/examples/security/Makefile
  metricbeat/templates/deployment.yaml
Labels: meta

#904 Helm 3 (#516)
  README.md
  apm-server/README.md
  apm-server/examples/default/Makefile
  apm-server/examples/oss/Makefile
  apm-server/examples/security/Makefile
  apm-server/templates/_helpers.tpl
  elasticsearch/README.md
  elasticsearch/examples/config/Makefile
  elasticsearch/examples/default/Makefile
  elasticsearch/examples/docker-for-mac/Makefile
  elasticsearch/examples/kubernetes-kind/Makefile
  elasticsearch/examples/microk8s/Makefile
  elasticsearch/examples/migration/Makefile
  elasticsearch/examples/minikube/Makefile
  elasticsearch/examples/multi/Makefile
  elasticsearch/examples/openshift/Makefile
  elasticsearch/examples/oss/Makefile
  elasticsearch/examples/security/Makefile
  elasticsearch/templates/NOTES.txt
  elasticsearch/templates/_helpers.tpl
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  filebeat/README.md
  filebeat/examples/default/Makefile
  filebeat/examples/oss/Makefile
  filebeat/examples/security/Makefile
  helpers/common.mk
  helpers/helm-tester/Dockerfile
  helpers/helpers.py
  helpers/terraform/Dockerfile
  helpers/terraform/Makefile
  kibana/README.md
  kibana/examples/default/Makefile
  kibana/examples/openshift/Makefile
  kibana/examples/oss/Makefile
  kibana/examples/security/Makefile
  kibana/templates/_helpers.tpl
  logstash/README.md
  logstash/examples/default/Makefile
  logstash/examples/elasticsearch/Makefile
  logstash/examples/oss/Makefile
  logstash/examples/security/Makefile
  logstash/templates/_helpers.tpl
  logstash/templates/service.yaml
  metricbeat/README.md
  metricbeat/examples/default/Makefile
  metricbeat/examples/oss/Makefile
  metricbeat/examples/security/Makefile
  metricbeat/templates/deployment.yaml
Labels: meta

#910 [meta] add link to eck chart doc
  README.md
Labels: doc, meta

#911 [elasticsearch] update test hook annotations
  elasticsearch/templates/test/test-elasticsearch-health.yaml
Labels: elasticsearch, helm3

#897 [elasticsearch] Fix spelling
  elasticsearch/values.yaml
Labels: doc, elasticsearch

#914 [meta] initiate 7.10 branch
  CONTRIBUTING.md
  README.md
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/migration/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/security/README.md
  elasticsearch/examples/upgrade/README.md
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/templates/daemonset.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/examples/security/README.md
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/templates/daemonset.yaml
Labels: meta

#907 [meta] upgrade test
  apm-server/examples/upgrade/Makefile
  apm-server/examples/upgrade/README.md
  apm-server/examples/upgrade/test/goss.yaml
  apm-server/examples/upgrade/values.yaml
  elasticsearch/examples/upgrade/Makefile
  elasticsearch/examples/upgrade/README.md
  elasticsearch/examples/upgrade/test/goss.yaml
  elasticsearch/examples/upgrade/values.yaml
  filebeat/examples/upgrade/Makefile
  filebeat/examples/upgrade/README.md
  filebeat/examples/upgrade/test/goss.yaml
  filebeat/examples/upgrade/values.yaml
  helpers/matrix.yml
  helpers/upgrade.sh
  kibana/examples/upgrade/Makefile
  kibana/examples/upgrade/README.md
  kibana/examples/upgrade/test/goss.yaml
  kibana/examples/upgrade/values.yaml
  logstash/examples/upgrade/Makefile
  logstash/examples/upgrade/README.md
  logstash/examples/upgrade/test/goss.yaml
  logstash/examples/upgrade/values.yaml
  metricbeat/examples/upgrade/Makefile
  metricbeat/examples/upgrade/README.md
  metricbeat/examples/upgrade/test/goss-metrics.yaml
  metricbeat/examples/upgrade/test/goss.yaml
  metricbeat/examples/upgrade/values.yaml
Labels: meta

#916 [meta] remove support for k8s <1.14 & helm <2.17.0
  apm-server/README.md
  apm-server/templates/_helpers.tpl
  apm-server/templates/hpa.yaml
  apm-server/templates/ingress.yaml
  elasticsearch/README.md
  elasticsearch/templates/_helpers.tpl
  elasticsearch/templates/ingress.yaml
  elasticsearch/templates/statefulset.yaml
  filebeat/README.md
  kibana/README.md
  kibana/templates/_helpers.tpl
  kibana/templates/ingress.yaml
  logstash/README.md
  logstash/templates/_helpers.tpl
  logstash/templates/ingress.yaml
  logstash/templates/statefulset.yaml
  metricbeat/README.md
Labels: breaking change, meta, v6.8.14, v7.10.0

#923 [7.x] [meta] remove support for k8s <1.14 & helm <2.17.0 (#916)
  apm-server/README.md
  apm-server/templates/_helpers.tpl
  apm-server/templates/hpa.yaml
  apm-server/templates/ingress.yaml
  elasticsearch/README.md
  elasticsearch/templates/_helpers.tpl
  elasticsearch/templates/ingress.yaml
  elasticsearch/templates/statefulset.yaml
  filebeat/README.md
  kibana/README.md
  kibana/templates/_helpers.tpl
  kibana/templates/ingress.yaml
  logstash/README.md
  logstash/templates/_helpers.tpl
  logstash/templates/ingress.yaml
  logstash/templates/statefulset.yaml
  metricbeat/README.md
Labels: backport

#922 [7.10] [meta] remove support for k8s <1.14 & helm <2.17.0 (#916)
  apm-server/README.md
  apm-server/templates/_helpers.tpl
  apm-server/templates/hpa.yaml
  apm-server/templates/ingress.yaml
  elasticsearch/README.md
  elasticsearch/templates/_helpers.tpl
  elasticsearch/templates/ingress.yaml
  elasticsearch/templates/statefulset.yaml
  filebeat/README.md
  kibana/README.md
  kibana/templates/_helpers.tpl
  kibana/templates/ingress.yaml
  logstash/README.md
  logstash/templates/_helpers.tpl
  logstash/templates/ingress.yaml
  logstash/templates/statefulset.yaml
  metricbeat/README.md
Labels: backport

#918 [6.8] [meta] upgrade test (#907)
  apm-server/examples/upgrade/Makefile
  apm-server/examples/upgrade/README.md
  apm-server/examples/upgrade/test/goss.yaml
  apm-server/examples/upgrade/values.yaml
  elasticsearch/examples/upgrade/Makefile
  elasticsearch/examples/upgrade/README.md
  elasticsearch/examples/upgrade/test/goss.yaml
  elasticsearch/examples/upgrade/values.yaml
  filebeat/examples/upgrade/Makefile
  filebeat/examples/upgrade/README.md
  filebeat/examples/upgrade/test/goss.yaml
  filebeat/examples/upgrade/values.yaml
  helpers/matrix.yml
  helpers/upgrade.sh
  kibana/examples/upgrade/Makefile
  kibana/examples/upgrade/README.md
  kibana/examples/upgrade/test/goss.yaml
  kibana/examples/upgrade/values.yaml
  logstash/examples/upgrade/Makefile
  logstash/examples/upgrade/README.md
  logstash/examples/upgrade/test/goss.yaml
  logstash/examples/upgrade/values.yaml
  metricbeat/examples/upgrade/Makefile
  metricbeat/examples/upgrade/README.md
  metricbeat/examples/upgrade/test/goss-metrics.yaml
  metricbeat/examples/upgrade/test/goss.yaml
  metricbeat/examples/upgrade/values.yaml
Labels: backport

#921 [6.8] [meta] remove support for k8s <1.14 & helm <2.17.0 (#916)
  apm-server/README.md
  apm-server/templates/_helpers.tpl
  apm-server/templates/hpa.yaml
  apm-server/templates/ingress.yaml
  elasticsearch/README.md
  elasticsearch/templates/_helpers.tpl
  elasticsearch/templates/ingress.yaml
  elasticsearch/templates/statefulset.yaml
  filebeat/README.md
  kibana/README.md
  kibana/templates/_helpers.tpl
  kibana/templates/ingress.yaml
  logstash/README.md
  logstash/templates/_helpers.tpl
  logstash/templates/ingress.yaml
  logstash/templates/statefulset.yaml
  metricbeat/README.md
Labels: backport

#927 [meta] remove version from dev install section title
  apm-server/README.md
  elasticsearch/README.md
  filebeat/README.md
  kibana/README.md
  logstash/README.md
  metricbeat/README.md
Labels: meta

#928 [meta] remove version from dev install section title
  apm-server/README.md
  elasticsearch/README.md
  filebeat/README.md
  kibana/README.md
  logstash/README.md
  metricbeat/README.md
Labels: meta

#930 7.10.0 release changelog
  BREAKING_CHANGES.md
  CHANGELOG.md
  README.md
Labels: meta

#929 7.10.0 release
  apm-server/Chart.yaml
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  apm-server/values.yaml
  elasticsearch/Chart.yaml
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/default/test/goss.yaml
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/security/README.md
  elasticsearch/examples/upgrade/test/goss.yaml
  elasticsearch/values.yaml
  filebeat/Chart.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/values.yaml
  helpers/examples.mk
  kibana/Chart.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  kibana/values.yaml
  logstash/Chart.yaml
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/examples/security/README.md
  logstash/values.yaml
  metricbeat/Chart.yaml
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/values.yaml
Labels: meta

#764 [logstash] add rbac custom annotations
  logstash/templates/serviceaccount.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: enhancement, logstash

#795 ES Statefulset empty initContainers fix
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
Labels: elasticsearch, enhancement

#935 [meta] stabilize CI tests
  .github/ISSUE_TEMPLATE/bug_report.md
  apm-server/examples/default/Makefile
  apm-server/examples/oss/Makefile
  apm-server/examples/security/Makefile
  apm-server/examples/upgrade/Makefile
  elasticsearch/examples/config/Makefile
  elasticsearch/examples/config/test/goss.yaml
  elasticsearch/examples/default/Makefile
  elasticsearch/examples/default/test/goss.yaml
  elasticsearch/examples/docker-for-mac/Makefile
  elasticsearch/examples/kubernetes-kind/Makefile
  elasticsearch/examples/microk8s/Makefile
  elasticsearch/examples/migration/Makefile
  elasticsearch/examples/migration/README.md
  elasticsearch/examples/migration/client.yaml
  elasticsearch/examples/migration/data.yaml
  elasticsearch/examples/migration/master.yaml
  elasticsearch/examples/minikube/Makefile
  elasticsearch/examples/multi/Makefile
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/multi/client.yaml
  elasticsearch/examples/multi/data.yaml
  elasticsearch/examples/multi/master.yaml
  elasticsearch/examples/openshift/Makefile
  elasticsearch/examples/openshift/test/goss.yaml
  elasticsearch/examples/oss/Makefile
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/security/Makefile
  elasticsearch/examples/security/test/goss.yaml
  elasticsearch/examples/security/values.yaml
  elasticsearch/examples/upgrade/Makefile
  elasticsearch/examples/upgrade/test/goss.yaml
  filebeat/examples/default/Makefile
  filebeat/examples/oss/Makefile
  filebeat/examples/security/Makefile
  filebeat/examples/upgrade/Makefile
  helpers/examples.mk
  kibana/examples/default/Makefile
  kibana/examples/openshift/Makefile
  kibana/examples/oss/Makefile
  kibana/examples/oss/values.yaml
  kibana/examples/security/Makefile
  kibana/examples/security/README.md
  kibana/examples/security/values.yaml
  kibana/examples/upgrade/Makefile
  logstash/examples/default/Makefile
  logstash/examples/default/test/goss.yaml
  logstash/examples/elasticsearch/Makefile
  logstash/examples/elasticsearch/test/goss.yaml
  logstash/examples/oss/Makefile
  logstash/examples/oss/test/goss.yaml
  logstash/examples/security/Makefile
  logstash/examples/security/test/goss.yaml
  logstash/examples/upgrade/Makefile
  logstash/examples/upgrade/test/goss.yaml
  metricbeat/examples/default/Makefile
  metricbeat/examples/oss/Makefile
  metricbeat/examples/security/Makefile
  metricbeat/examples/upgrade/Makefile
Labels: meta

#936 [6.8] [meta] stabilize CI tests (#935)
  .github/ISSUE_TEMPLATE/bug_report.md
  apm-server/examples/default/Makefile
  apm-server/examples/oss/Makefile
  apm-server/examples/security/Makefile
  apm-server/examples/upgrade/Makefile
  elasticsearch/examples/config/Makefile
  elasticsearch/examples/config/test/goss.yaml
  elasticsearch/examples/default/Makefile
  elasticsearch/examples/default/test/goss.yaml
  elasticsearch/examples/docker-for-mac/Makefile
  elasticsearch/examples/kubernetes-kind/Makefile
  elasticsearch/examples/microk8s/Makefile
  elasticsearch/examples/migration/Makefile
  elasticsearch/examples/migration/README.md
  elasticsearch/examples/migration/client.yaml
  elasticsearch/examples/migration/data.yaml
  elasticsearch/examples/migration/master.yaml
  elasticsearch/examples/minikube/Makefile
  elasticsearch/examples/multi/Makefile
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/multi/client.yaml
  elasticsearch/examples/multi/data.yaml
  elasticsearch/examples/multi/master.yaml
  elasticsearch/examples/openshift/Makefile
  elasticsearch/examples/openshift/test/goss.yaml
  elasticsearch/examples/oss/Makefile
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/security/Makefile
  elasticsearch/examples/security/test/goss.yaml
  elasticsearch/examples/security/values.yaml
  elasticsearch/examples/upgrade/Makefile
  elasticsearch/examples/upgrade/test/goss.yaml
  filebeat/examples/default/Makefile
  filebeat/examples/oss/Makefile
  filebeat/examples/security/Makefile
  filebeat/examples/upgrade/Makefile
  helpers/examples.mk
  kibana/examples/default/Makefile
  kibana/examples/openshift/Makefile
  kibana/examples/oss/Makefile
  kibana/examples/oss/values.yaml
  kibana/examples/security/Makefile
  kibana/examples/security/README.md
  kibana/examples/security/values.yaml
  kibana/examples/upgrade/Makefile
  logstash/examples/default/Makefile
  logstash/examples/default/test/goss.yaml
  logstash/examples/elasticsearch/Makefile
  logstash/examples/elasticsearch/test/goss.yaml
  logstash/examples/oss/Makefile
  logstash/examples/security/Makefile
  logstash/examples/security/test/goss.yaml
  logstash/examples/upgrade/Makefile
  metricbeat/examples/default/Makefile
  metricbeat/examples/oss/Makefile
  metricbeat/examples/security/Makefile
  metricbeat/examples/upgrade/Makefile
Labels: backport

#937 [7.10] [meta] stabilize CI tests (#935)
  .github/ISSUE_TEMPLATE/bug_report.md
  apm-server/examples/default/Makefile
  apm-server/examples/oss/Makefile
  apm-server/examples/security/Makefile
  apm-server/examples/upgrade/Makefile
  elasticsearch/examples/config/Makefile
  elasticsearch/examples/config/test/goss.yaml
  elasticsearch/examples/default/Makefile
  elasticsearch/examples/default/test/goss.yaml
  elasticsearch/examples/docker-for-mac/Makefile
  elasticsearch/examples/kubernetes-kind/Makefile
  elasticsearch/examples/microk8s/Makefile
  elasticsearch/examples/migration/Makefile
  elasticsearch/examples/migration/README.md
  elasticsearch/examples/migration/client.yaml
  elasticsearch/examples/migration/data.yaml
  elasticsearch/examples/migration/master.yaml
  elasticsearch/examples/minikube/Makefile
  elasticsearch/examples/multi/Makefile
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/multi/client.yaml
  elasticsearch/examples/multi/data.yaml
  elasticsearch/examples/multi/master.yaml
  elasticsearch/examples/openshift/Makefile
  elasticsearch/examples/openshift/test/goss.yaml
  elasticsearch/examples/oss/Makefile
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/security/Makefile
  elasticsearch/examples/security/test/goss.yaml
  elasticsearch/examples/security/values.yaml
  elasticsearch/examples/upgrade/Makefile
  elasticsearch/examples/upgrade/test/goss.yaml
  filebeat/examples/default/Makefile
  filebeat/examples/oss/Makefile
  filebeat/examples/security/Makefile
  filebeat/examples/upgrade/Makefile
  helpers/examples.mk
  kibana/examples/default/Makefile
  kibana/examples/openshift/Makefile
  kibana/examples/oss/Makefile
  kibana/examples/oss/values.yaml
  kibana/examples/security/Makefile
  kibana/examples/security/README.md
  kibana/examples/security/values.yaml
  kibana/examples/upgrade/Makefile
  logstash/examples/default/Makefile
  logstash/examples/default/test/goss.yaml
  logstash/examples/elasticsearch/Makefile
  logstash/examples/elasticsearch/test/goss.yaml
  logstash/examples/oss/Makefile
  logstash/examples/oss/test/goss.yaml
  logstash/examples/security/Makefile
  logstash/examples/security/test/goss.yaml
  logstash/examples/upgrade/Makefile
  logstash/examples/upgrade/test/goss.yaml
  metricbeat/examples/default/Makefile
  metricbeat/examples/oss/Makefile
  metricbeat/examples/security/Makefile
  metricbeat/examples/upgrade/Makefile
Labels: backport

#938 [7.x] [meta] stabilize CI tests (#935)
  .github/ISSUE_TEMPLATE/bug_report.md
  apm-server/examples/default/Makefile
  apm-server/examples/oss/Makefile
  apm-server/examples/security/Makefile
  apm-server/examples/upgrade/Makefile
  elasticsearch/examples/config/Makefile
  elasticsearch/examples/config/test/goss.yaml
  elasticsearch/examples/default/Makefile
  elasticsearch/examples/default/test/goss.yaml
  elasticsearch/examples/docker-for-mac/Makefile
  elasticsearch/examples/kubernetes-kind/Makefile
  elasticsearch/examples/microk8s/Makefile
  elasticsearch/examples/migration/Makefile
  elasticsearch/examples/migration/README.md
  elasticsearch/examples/migration/client.yaml
  elasticsearch/examples/migration/data.yaml
  elasticsearch/examples/migration/master.yaml
  elasticsearch/examples/minikube/Makefile
  elasticsearch/examples/multi/Makefile
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/multi/client.yaml
  elasticsearch/examples/multi/data.yaml
  elasticsearch/examples/multi/master.yaml
  elasticsearch/examples/openshift/Makefile
  elasticsearch/examples/openshift/test/goss.yaml
  elasticsearch/examples/oss/Makefile
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/security/Makefile
  elasticsearch/examples/security/test/goss.yaml
  elasticsearch/examples/security/values.yaml
  elasticsearch/examples/upgrade/Makefile
  elasticsearch/examples/upgrade/test/goss.yaml
  filebeat/examples/default/Makefile
  filebeat/examples/oss/Makefile
  filebeat/examples/security/Makefile
  filebeat/examples/upgrade/Makefile
  helpers/examples.mk
  kibana/examples/default/Makefile
  kibana/examples/openshift/Makefile
  kibana/examples/oss/Makefile
  kibana/examples/oss/values.yaml
  kibana/examples/security/Makefile
  kibana/examples/security/README.md
  kibana/examples/security/values.yaml
  kibana/examples/upgrade/Makefile
  logstash/examples/default/Makefile
  logstash/examples/default/test/goss.yaml
  logstash/examples/elasticsearch/Makefile
  logstash/examples/elasticsearch/test/goss.yaml
  logstash/examples/oss/Makefile
  logstash/examples/oss/test/goss.yaml
  logstash/examples/security/Makefile
  logstash/examples/security/test/goss.yaml
  logstash/examples/upgrade/Makefile
  logstash/examples/upgrade/test/goss.yaml
  metricbeat/examples/default/Makefile
  metricbeat/examples/oss/Makefile
  metricbeat/examples/security/Makefile
  metricbeat/examples/upgrade/Makefile
Labels: backport

#939 [meta] allows concurrent jobs for pr
  .ci/jobs/elastic+helm-charts+pull-request+cluster-cleanup.yml
  .ci/jobs/elastic+helm-charts+pull-request+cluster-creation.yml
  .ci/jobs/elastic+helm-charts+pull-request+integration-apm-server.yml
  .ci/jobs/elastic+helm-charts+pull-request+integration-elasticsearch.yml
  .ci/jobs/elastic+helm-charts+pull-request+integration-filebeat.yml
  .ci/jobs/elastic+helm-charts+pull-request+integration-kibana.yml
  .ci/jobs/elastic+helm-charts+pull-request+integration-logstash.yml
  .ci/jobs/elastic+helm-charts+pull-request+integration-metricbeat.yml
  .ci/jobs/elastic+helm-charts+pull-request+lint-python.yml
  .ci/jobs/elastic+helm-charts+pull-request+template-testing.yml
Labels: meta, need-backport

#943 [7.x] ES Statefulset empty initContainers fix (#795)
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
Labels: backport

#942 [7.10] ES Statefulset empty initContainers fix (#795)
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
Labels: backport

#941 [6.8] ES Statefulset empty initContainers fix (#795)
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
Labels: backport

#946 [7.x] [logstash] add rbac custom annotations (#764)
  logstash/templates/serviceaccount.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#945 [7.10] [logstash] add rbac custom annotations (#764)
  logstash/templates/serviceaccount.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#944 [6.8] [logstash] add rbac custom annotations (#764)
  logstash/templates/serviceaccount.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport
