Repository elastic/helm-charts, pull requests merged in 2020-06, with the labels that each got.

#650 7.7.1 Release
  apm-server/Chart.yaml
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  apm-server/values.yaml
  elasticsearch/Chart.yaml
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/default/test/goss.yaml
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/security/README.md
  elasticsearch/examples/upgrade/README.md
  elasticsearch/examples/upgrade/test/goss.yaml
  elasticsearch/values.yaml
  filebeat/Chart.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/values.yaml
  helpers/bumper.py
  helpers/examples.mk
  kibana/Chart.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  kibana/values.yaml
  logstash/Chart.yaml
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/values.yaml
  metricbeat/Chart.yaml
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/values.yaml
Labels: meta

#651 6.8.10 Release
  apm-server/Chart.yaml
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  apm-server/values.yaml
  elasticsearch/Chart.yaml
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/security/README.md
  elasticsearch/values.yaml
  filebeat/Chart.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/values.yaml
  helpers/bumper.py
  helpers/examples.mk
  kibana/Chart.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  kibana/values.yaml
  logstash/Chart.yaml
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/values.yaml
  metricbeat/Chart.yaml
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/values.yaml
Labels: meta

#437 Elasticsearch: do not include heritage selector
  elasticsearch/templates/service.yaml
Labels: enhancement

#657 [helm] bump helm version to 2.16.8
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: meta, v6.8.11, v7.8.0

#660 initiate 7.8 branch
  BREAKING_CHANGES.md
  README.md
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/migration/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/security/README.md
  elasticsearch/examples/upgrade/README.md
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  helpers/bumper.py
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
Labels: meta

#662 [doc] fix release install commands
  apm-server/README.md
  elasticsearch/README.md
  filebeat/README.md
  kibana/README.md
  logstash/README.md
  metricbeat/README.md
Labels: doc

#664 [apm-server] increase memory limit
  apm-server/values.yaml
Labels: apm-server, enhancement

#542 Disable service links to prevent very long startup times
  elasticsearch/README.md
  elasticsearch/templates/statefulset.yaml
  elasticsearch/values.yaml
Labels: enhancement

#671 [apm-server] allow customizing probes
  apm-server/templates/deployment.yaml
  apm-server/values.yaml
Labels: v6.8.11, v7.8.0

#669 [elasticsearch] update kind example for version >= 0.7.0
  elasticsearch/examples/kubernetes-kind/Makefile
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/kubernetes-kind/values-local-path.yaml
Labels: enhancement, v6.8.11, v7.8.0

#667 [helm] bump helm version to 2.16.9
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: meta, v6.8.11, v7.8.0

#392 [logstash] add security example
  elasticsearch/examples/security/Makefile
  helpers/matrix.yml
  logstash/examples/security/Makefile
  logstash/examples/security/README.md
  logstash/examples/security/test/goss.yaml
  logstash/examples/security/values.yaml
Labels: feature request, v6.8.11, v7.8.0

#674 [meta] update changelog for 7.8.0 release
  BREAKING_CHANGES.md
  CHANGELOG.md
Labels: meta

#673 7.8.0 Release
  apm-server/Chart.yaml
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  apm-server/values.yaml
  elasticsearch/Chart.yaml
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/default/test/goss.yaml
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/security/README.md
  elasticsearch/examples/upgrade/README.md
  elasticsearch/examples/upgrade/test/goss.yaml
  elasticsearch/values.yaml
  filebeat/Chart.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/values.yaml
  helpers/bumper.py
  helpers/examples.mk
  kibana/Chart.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  kibana/values.yaml
  logstash/Chart.yaml
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/examples/security/README.md
  logstash/examples/security/test/goss.yaml
  logstash/values.yaml
  metricbeat/Chart.yaml
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/values.yaml
Labels: meta

#679 Update Readme
  kibana/README.md
Labels: doc, kibana

#678 Update readme
  elasticsearch/README.md
Labels: doc, elasticsearch

#687 [meta] disable stackdriver for gke test clusters
  helpers/terraform/main.tf
Labels: meta

#692 [doc] add back beta notices for 6.8
  README.md
  elasticsearch/README.md
  filebeat/README.md
  kibana/README.md
  metricbeat/README.md
Labels: doc

#693 [doc] fix ga support mentions for 6.8.9
  CHANGELOG.md
  README.md
Labels: doc

#686 Add ServiceAccount annotations
  apm-server/README.md
  apm-server/templates/serviceaccount.yaml
  apm-server/tests/apmserver_test.py
  apm-server/values.yaml
  elasticsearch/templates/serviceaccount.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/templates/serviceaccount.yaml
  filebeat/tests/filebeat_test.py
  filebeat/values.yaml
  logstash/templates/serviceaccount.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
  metricbeat/README.md
  metricbeat/templates/serviceaccount.yaml
  metricbeat/tests/metricbeat_test.py
  metricbeat/values.yaml
Labels: elasticsearch, enhancement, logstash

#696 [logstash] fix version in security test
  logstash/examples/security/test/goss.yaml
Labels: bug, logstash

#697 [logstash] fix version in security test
  logstash/examples/security/test/goss.yaml
Labels: bug, logstash

#690 [docs] Improve visibility of 6.8 and 7.x releases
  README.md
Labels: doc

#695 [logstash] add headless service for statefulset
  logstash/templates/service-headless.yaml
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
Labels: breaking change, logstash

#700 [doc] fix copy-paste errors
  kibana/README.md
  logstash/README.md
Labels: doc
