Repository elastic/helm-charts, pull requests merged in 2020-12, with the labels that each got.

#940 [meta] enable metricbeat upgrade test
  helpers/matrix.yml
  metricbeat/examples/upgrade/Makefile
Labels: meta, metricbeat, need-backport

#950 [7.10] [meta] enable metricbeat upgrade test (#940)
  helpers/matrix.yml
  metricbeat/examples/upgrade/Makefile
Labels: backport

#951 [7.x] [meta] enable metricbeat upgrade test (#940)
  helpers/matrix.yml
  metricbeat/examples/upgrade/Makefile
Labels: backport

#782 [apm-server] Add missing fields to HPA
  apm-server/README.md
  apm-server/templates/hpa.yaml
  apm-server/tests/apmserver_test.py
  apm-server/values.yaml
Labels: apm-server, bug

#954 [6.8] [apm-server] Add missing fields to HPA (#782)
  apm-server/README.md
  apm-server/templates/hpa.yaml
  apm-server/tests/apmserver_test.py
  apm-server/values.yaml
Labels: backport

#955 [7.10] [apm-server] Add missing fields to HPA (#782)
  apm-server/README.md
  apm-server/templates/hpa.yaml
  apm-server/tests/apmserver_test.py
  apm-server/values.yaml
Labels: backport

#956 [7.x] [apm-server] Add missing fields to HPA (#782)
  apm-server/README.md
  apm-server/templates/hpa.yaml
  apm-server/tests/apmserver_test.py
  apm-server/values.yaml
Labels: backport

#957 [6.8] [kibana] add service.httpPortName config in chart (#843)
  kibana/templates/service.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: backport

#958 [7.10] [kibana] add service.httpPortName config in chart (#843)
  kibana/templates/service.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: backport

#959 [7.x] [kibana] add service.httpPortName config in chart (#843)
  kibana/templates/service.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: backport

#971 [meta] add config for backport
  .backportrc.json
Labels: meta

#972 [6.8] [meta] add config for backport (#971)
  .backportrc.json
Labels: backport

#973 [7.10] [meta] add config for backport (#971)
  .backportrc.json
Labels: backport

#974 [7.x] [meta] add config for backport (#971)
  .backportrc.json
Labels: backport

#975 elasticsearch: add emptyDir to podSecurityPolicy as allowed volume-type
  elasticsearch/values.yaml
Labels: elasticsearch, enhancement, need-backport

#970 [all] add hostaliases
  apm-server/README.md
  apm-server/templates/deployment.yaml
  apm-server/tests/apmserver_test.py
  apm-server/values.yaml
  elasticsearch/README.md
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/templates/daemonset.yaml
  filebeat/tests/filebeat_test.py
  filebeat/values.yaml
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
  logstash/README.md
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
  metricbeat/README.md
  metricbeat/templates/daemonset.yaml
  metricbeat/templates/deployment.yaml
  metricbeat/tests/metricbeat_test.py
  metricbeat/values.yaml
Labels: apm-server, elasticsearch, feature, filebeat, kibana, logstash, metricbeat, need-backport, v6.8.15, v7.10.2

#977 [meta] bump helm to 3.4.2
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: meta, need-backport, v6.8.15, v7.10.2

#978 [filebeat] Configurable ClusterRole
  filebeat/README.md
  filebeat/templates/clusterrole.yaml
  filebeat/values.yaml
Labels: enhancement, filebeat

#986 [6.8] [meta] bump helm to 3.4.2 (#977)
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport

#987 [7.10] [meta] bump helm to 3.4.2 (#977)
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport

#988 [7.x] [meta] bump helm to 3.4.2 (#977)
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport

#980 [6.8] elasticsearch: add emptyDir to podSecurityPolicy as allowed volume-type (#975)
  elasticsearch/values.yaml
Labels: backport

#981 [7.10] elasticsearch: add emptyDir to podSecurityPolicy as allowed volume-type (#975)
  elasticsearch/values.yaml
Labels: backport

#982 [7.x] elasticsearch: add emptyDir to podSecurityPolicy as allowed volume-type (#975)
  elasticsearch/values.yaml
Labels: backport

#984 [7.10] [all] add hostaliases (#970)
  apm-server/README.md
  apm-server/templates/deployment.yaml
  apm-server/tests/apmserver_test.py
  apm-server/values.yaml
  elasticsearch/README.md
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/templates/daemonset.yaml
  filebeat/tests/filebeat_test.py
  filebeat/values.yaml
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
  logstash/README.md
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
  metricbeat/README.md
  metricbeat/templates/daemonset.yaml
  metricbeat/templates/deployment.yaml
  metricbeat/tests/metricbeat_test.py
  metricbeat/values.yaml
Labels: backport

#983 [6.8] [all] add hostaliases (#970)
  apm-server/README.md
  apm-server/templates/deployment.yaml
  apm-server/tests/apmserver_test.py
  apm-server/values.yaml
  elasticsearch/README.md
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/templates/daemonset.yaml
  filebeat/tests/filebeat_test.py
  filebeat/values.yaml
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
  logstash/README.md
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
  metricbeat/README.md
  metricbeat/templates/daemonset.yaml
  metricbeat/templates/deployment.yaml
  metricbeat/tests/metricbeat_test.py
  metricbeat/values.yaml
Labels: backport

#985 [7.x] [all] add hostaliases (#970)
  apm-server/README.md
  apm-server/templates/deployment.yaml
  apm-server/tests/apmserver_test.py
  apm-server/values.yaml
  elasticsearch/README.md
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/templates/daemonset.yaml
  filebeat/tests/filebeat_test.py
  filebeat/values.yaml
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
  logstash/README.md
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
  metricbeat/README.md
  metricbeat/templates/daemonset.yaml
  metricbeat/templates/deployment.yaml
  metricbeat/tests/metricbeat_test.py
  metricbeat/values.yaml
Labels: backport

#994 [elasticsearch][kibana] Add flexible ingress
  elasticsearch/templates/ingress.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
  kibana/templates/ingress.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: breaking change, elasticsearch, enhancement, kibana, need-backport
