Repository elastic/helm-charts, pull requests merged in 2020-05, with the labels that each got.

#607 [helm] bump helm version to 2.16.7
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: enhancement

#613 7.7.0 Release
  README.md
  apm-server/Chart.yaml
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  apm-server/values.yaml
  elasticsearch/Chart.yaml
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/default/test/goss.yaml
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/security/README.md
  elasticsearch/examples/upgrade/README.md
  elasticsearch/examples/upgrade/test/goss.yaml
  elasticsearch/values.yaml
  filebeat/Chart.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/examples/security/values.yaml
  filebeat/values.yaml
  helpers/bumper.py
  helpers/examples.mk
  kibana/Chart.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  kibana/values.yaml
  logstash/Chart.yaml
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/values.yaml
  metricbeat/Chart.yaml
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/values.yaml
Labels: meta

#615 [meta] update changelog and breaking changes for 6.8.9
  BREAKING_CHANGES.md
  CHANGELOG.md
Labels: meta

#617 6.8.9 Release
  README.md
  apm-server/Chart.yaml
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  apm-server/values.yaml
  elasticsearch/Chart.yaml
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/migration/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/security/README.md
  elasticsearch/values.yaml
  filebeat/Chart.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/values.yaml
  helpers/bumper.py
  helpers/examples.mk
  kibana/Chart.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  kibana/values.yaml
  logstash/Chart.yaml
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/values.yaml
  metricbeat/Chart.yaml
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/values.yaml
Labels: meta

#619 [meta] update changelog with GA mentions
  CHANGELOG.md
Labels: meta

#622 [metricbeat] fix deployment upgrade by removing chart label from .spec.selector.matchLabels
  BREAKING_CHANGES.md
  metricbeat/templates/deployment.yaml
Labels: bug, v7.7.1

#637 [kibana] String/YAML conditions for `.Values.{extraContainers,extraInitContainers}`
  kibana/templates/deployment.yaml
Labels: bug, kibana, v6.8.10, v7.7.1

#638 [elasticsearch] Fix issue with `readinessProbe` causing outages
  BREAKING_CHANGES.md
  elasticsearch/templates/statefulset.yaml
Labels: bug, elasticsearch, v6.8.10, v7.7.1

#624 [metricbeat] use deprecated kube-state-metrics config when existing
  BREAKING_CHANGES.md
  metricbeat/templates/deployment.yaml
  metricbeat/tests/metricbeat_test.py
Labels: bug, metricbeat, v6.8.10, v7.7.1

#596 Elasticsearch secret mountmode
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: elasticsearch, enhancement

#555 Add extensible label support on Kibana
  kibana/templates/_helpers.tpl
  kibana/templates/configmap.yaml
  kibana/templates/deployment.yaml
  kibana/templates/ingress.yaml
  kibana/templates/service.yaml
Labels: enhancement

#635 [meta] add support for k8s 1.16
  elasticsearch/examples/upgrade/Makefile
  elasticsearch/examples/upgrade/README.md
  elasticsearch/examples/upgrade/scripts/upgrade.sh
  helpers/matrix.yml
  helpers/terraform/Dockerfile
Labels: meta, v6.8.10, v7.7.1
