Repository elastic/helm-charts, pull requests merged in 2020-04, with the labels that each got.

#549 fix: allow redirection on the readinessProbe
  kibana/templates/deployment.yaml
Labels: bug

#471 Make use of secure port when accessing Kubelet API
  metricbeat/examples/security/values.yaml
  metricbeat/values.yaml
Labels: enhancement

#564 [elasticsearch] fix helm test command
  elasticsearch/templates/NOTES.txt
Labels: bug

#570 [meta] fix ci jobs
  .ci/jobs.t/elastic+helm-charts+{branch}+cluster-cleanup.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+cluster-creation.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+integration-apm-server.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+integration-elasticsearch.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+integration-filebeat.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+integration-kibana.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+integration-logstash.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+integration-metricbeat.yml
Labels: meta

#567 Metricbeat improvements
  .gitignore
  metricbeat/examples/6.x/test/goss.yaml
  metricbeat/examples/default/test/goss.yaml
  metricbeat/examples/oss/test/goss.yaml
  metricbeat/examples/security/test/goss.yaml
  metricbeat/examples/security/values.yaml
  metricbeat/templates/daemonset.yaml
  metricbeat/tests/metricbeat_test.py
  metricbeat/values.yaml
Labels: enhancement

#568 Filebeat improvements
  filebeat/examples/6.x/values.yaml
  filebeat/examples/security/values.yaml
  filebeat/templates/daemonset.yaml
  filebeat/values.yaml
Labels: enhancement

#580 [helm] bump helm version to 2.16.6
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: enhancement, v7.7.0

#581 [script] Update bumper script to handle SNAPSHOT versions
  apm-server/README.md
  elasticsearch/README.md
  filebeat/README.md
  helpers/bumper.py
  kibana/README.md
  logstash/README.md
  metricbeat/README.md
Labels: v7.7.0

#583 Use busybox for key generation in testing
  elasticsearch/examples/security/Makefile
  kibana/examples/security/Makefile
Labels: v7.7.0

#572 [metricbeat] split values for daemonset and deployment
  metricbeat/README.md
  metricbeat/examples/6.x/test/goss-metrics.yaml
  metricbeat/examples/default/test/goss-metrics.yaml
  metricbeat/examples/oss/test/goss-metrics.yaml
  metricbeat/examples/oss/values.yaml
  metricbeat/examples/security/test/goss-metrics.yaml
  metricbeat/examples/security/values.yaml
  metricbeat/templates/configmap.yaml
  metricbeat/templates/daemonset.yaml
  metricbeat/templates/deployment.yaml
  metricbeat/tests/metricbeat_test.py
  metricbeat/values.yaml
Labels: enhancement

#585 [metricbeat] add host networking option
  metricbeat/README.md
  metricbeat/templates/daemonset.yaml
  metricbeat/tests/metricbeat_test.py
  metricbeat/values.yaml
Labels: enhancement, v7.7.0

#590 [elasticsearch] Adds imagePullSecrets for test Pod
  elasticsearch/templates/test/test-elasticsearch-health.yaml
Labels: enhancement

#584 [elasticsearch] Set securityContext for test pod
  elasticsearch/templates/test/test-elasticsearch-health.yaml
Labels: enhancement

#522 Update defaults for extra values to support lists
  elasticsearch/README.md
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: enhancement

#586 [elasticsearch] update readiness probe endpoint
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
Labels: enhancement, v7.7.0

#569 Added support for envFrom in apm-server, logstash, kibana and elasticsearch
  apm-server/README.md
  apm-server/templates/deployment.yaml
  apm-server/tests/apmserver_test.py
  apm-server/values.yaml
  elasticsearch/README.md
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
  logstash/README.md
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: enhancement

#591 [logstash] update doc and values.yaml for http.host issues
  logstash/README.md
  logstash/values.yaml
Labels: enhancement

#599 Merge pull request #593 from jmlrt/doc-improvements
  CONTRIBUTING.md
  README.md
  apm-server/README.md
  elasticsearch/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/migration/README.md
  elasticsearch/values.yaml
  filebeat/README.md
  kibana/README.md
  kibana/values.yaml
  logstash/README.md
  metricbeat/README.md
  metricbeat/examples/default/README.md
Labels: enhancement, v7.7.0

#598 FAQ and examples improvements
  CONTRIBUTING.md
  README.md
  apm-server/README.md
  apm-server/examples/6.x/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  elasticsearch/README.md
  elasticsearch/examples/6.x/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/migration/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/security/README.md
  elasticsearch/examples/upgrade/README.md
  filebeat/README.md
  filebeat/examples/6.x/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  kibana/README.md
  kibana/examples/6.x/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  logstash/README.md
  logstash/examples/6.x/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  metricbeat/README.md
  metricbeat/examples/6.x/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
Labels: enhancement, v7.7.0

#600 FAQ and examples improvements (#598)
  CONTRIBUTING.md
  README.md
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/security/README.md
  elasticsearch/examples/upgrade/README.md
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  metricbeat/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
Labels: enhancement, v7.7.0

#601 [meta] bump version on examples readme
  helpers/bumper.py
Labels: enhancement, v7.7.0
