Repository elastic/helm-charts, pull requests merged in 2020-01, with the labels that each got.

#430 Correct default value of extraVolumeMounts and extraVolumes in filebeat/README.md
  filebeat/README.md
Labels: enhancement

#408 [kibana] add support for loadBalancerSourceRanges
  kibana/README.md
  kibana/templates/service.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: enhancement

#433 [elasticsearch] add example for microk8s
  elasticsearch/README.md
  elasticsearch/examples/microk8s/Makefile
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/microk8s/values.yaml
Labels: enhancement

#419 [kibana] add doc for plugin install
  kibana/README.md
Labels: enhancement

#421 [botelastic] add probot config to manage stale issues/pr
  .github/stale.yml
Labels: enhancement

#434 [elasticsearch] add workaround to fix kind example
  elasticsearch/examples/kubernetes-kind/Makefile
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/kubernetes-kind/values.yaml
Labels: bug

#435 [meta] add k8s 1.15 and drop k8s 1.12
  helpers/matrix.yml
  helpers/terraform/Dockerfile
  helpers/terraform/Makefile
Labels: enhancement

#438 [doc] switch relative URLs to absolute URLs
  elasticsearch/README.md
  filebeat/README.md
  kibana/README.md
  logstash/README.md
  metricbeat/README.md
Labels: enhancement

#454 7.5.2 release
  CHANGELOG.md
  elasticsearch/Chart.yaml
  elasticsearch/README.md
  elasticsearch/examples/default/test/goss.yaml
  elasticsearch/examples/microk8s/values.yaml
  elasticsearch/examples/openshift/test/goss.yaml
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/upgrade/test/goss.yaml
  elasticsearch/values.yaml
  filebeat/Chart.yaml
  filebeat/README.md
  filebeat/examples/default/test/goss.yaml
  filebeat/examples/oss/test/goss.yaml
  filebeat/examples/security/test/goss.yaml
  filebeat/values.yaml
  helpers/bumper.py
  helpers/examples.mk
  kibana/Chart.yaml
  kibana/README.md
  kibana/examples/default/test/goss.yaml
  kibana/values.yaml
  logstash/Chart.yaml
  logstash/README.md
  logstash/examples/default/test/goss.yaml
  logstash/examples/elasticsearch/test/goss.yaml
  logstash/examples/oss/test/goss.yaml
  logstash/values.yaml
  metricbeat/Chart.yaml
  metricbeat/README.md
  metricbeat/examples/default/test/goss-metrics.yaml
  metricbeat/examples/default/test/goss.yaml
  metricbeat/examples/oss/test/goss-metrics.yaml
  metricbeat/examples/oss/test/goss.yaml
  metricbeat/examples/security/test/goss-metrics.yaml
  metricbeat/examples/security/test/goss.yaml
  metricbeat/values.yaml
Labels: enhancement

#459 [apm-server] add ci tests for apm-server chart
  .ci/jobs/elastic+helm-charts+master+integration-apm-server.yml
  .ci/jobs/elastic+helm-charts+master.yml
  .ci/jobs/elastic+helm-charts+pull-request+integration-apm-server.yml
  .ci/jobs/elastic+helm-charts+pull-request.yml
  helpers/matrix.yml
Labels: feature request

#324 add apm-server helm chart
  README.md
  apm-server/.helmignore
  apm-server/Chart.yaml
  apm-server/Makefile
  apm-server/README.md
  apm-server/examples/6.x/Makefile
  apm-server/examples/6.x/test/goss.yaml
  apm-server/examples/6.x/values.yaml
  apm-server/examples/default/Makefile
  apm-server/examples/default/test/goss.yaml
  apm-server/examples/oss/Makefile
  apm-server/examples/oss/test/goss.yaml
  apm-server/examples/oss/values.yaml
  apm-server/examples/security/Makefile
  apm-server/examples/security/test/goss.yaml
  apm-server/examples/security/values.yaml
  apm-server/templates/NOTES.txt
  apm-server/templates/_helpers.tpl
  apm-server/templates/clusterrole.yaml
  apm-server/templates/clusterrolebinding.yaml
  apm-server/templates/configmap.yaml
  apm-server/templates/deployment.yaml
  apm-server/templates/hpa.yaml
  apm-server/templates/ingress.yaml
  apm-server/templates/service.yaml
  apm-server/templates/serviceaccount.yaml
  apm-server/tests/apmserver_test.py
  apm-server/values.yaml
Labels: feature request

#461 [apm-server] bump to 7.5.2
  apm-server/Chart.yaml
  apm-server/README.md
  apm-server/examples/6.x/test/goss.yaml
  apm-server/examples/default/test/goss.yaml
  apm-server/examples/oss/test/goss.yaml
  apm-server/examples/oss/values.yaml
  apm-server/examples/security/test/goss.yaml
  apm-server/values.yaml
Labels: enhancement
