Repository elastic/helm-charts, pull requests merged in 2020-09, with the labels that each got.

#799 [meta] remove ci tests for 7.8 branch
  .ci/jobs.t/defaults.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+cluster-cleanup.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+cluster-creation.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+integration-apm-server.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+integration-elasticsearch.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+integration-filebeat.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+integration-kibana.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+integration-logstash.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+integration-metricbeat.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+template-lint-python.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+template-testing.yml
  .ci/jobs.t/elastic+helm-charts+{branch}.yml
  .ci/make-branch-config.sh
  .ci/views/views.yml
Labels: meta

#800 [meta] Update changelog for 7.8.1 / 7.9.0 / 6.8.11 / 6.8.12 releases
  BREAKING_CHANGES.md
  CHANGELOG.md
Labels: meta

#803 7.9.1 release
  README.md
  apm-server/Chart.yaml
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  apm-server/values.yaml
  elasticsearch/Chart.yaml
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/default/test/goss.yaml
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/security/README.md
  elasticsearch/examples/upgrade/README.md
  elasticsearch/examples/upgrade/test/goss.yaml
  elasticsearch/values.yaml
  filebeat/Chart.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/values.yaml
  helpers/examples.mk
  kibana/Chart.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  kibana/values.yaml
  logstash/Chart.yaml
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/examples/security/README.md
  logstash/values.yaml
  metricbeat/Chart.yaml
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/values.yaml
Labels: 7.9.1, meta

#804 [meta] update changelog for 7.9.1 release
  CHANGELOG.md
  README.md
Labels: 7.9.1, meta

#778 [metricbeat] Support secrets
  metricbeat/README.md
  metricbeat/templates/secret.yaml
  metricbeat/tests/metricbeat_test.py
  metricbeat/values.yaml
Labels: 7.9.1, feature request, metricbeat

#729 Include pre-releases in the semver range.
  elasticsearch/templates/statefulset.yaml
Labels: bug, elasticsearch

#811 [elasticsearch] fix secrets names in examples
  elasticsearch/README.md
Labels: bug, doc, elasticsearch

#816 [helm] bump helm version to 2.16.12
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: meta

#818 [elasticsearch][kibana] disable nss dentry cache
  elasticsearch/templates/statefulset.yaml
  kibana/templates/deployment.yaml
Labels: bug, elasticsearch, kibana
