Repository elastic/helm-charts, pull requests merged in 2020-07, with the labels that each got.

#704 [filebeat] add permission to list nodes
  filebeat/templates/clusterrole.yaml
Labels: enhancement, filebeat

#715 [testing] Ensure that the 'namespace' is specified in Helm command
  helpers/helpers.py
Labels: v6.8.11, v7.8.1

#713 feat(metricbeat): annotation support for daemonset and deployment
  metricbeat/README.md
  metricbeat/templates/daemonset.yaml
  metricbeat/templates/deployment.yaml
  metricbeat/tests/metricbeat_test.py
  metricbeat/values.yaml
Labels: enhancement, metricbeat, v6.8.11, v7.8.1, v7.9.0

#708 [apm-server] Add to test matrix
  helpers/matrix.yml
Labels: apm-server, v6.8.11, v7.8.1, v7.9.0

#712 Support creating k8s helm secrets for logstash helm chart #705
  logstash/README.md
  logstash/templates/secret.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: enhancement, logstash, v6.8.11, v7.8.1, v7.9.0

#699 [filebeat] document probe workaround for kafka output
  filebeat/README.md
Labels: doc, filebeat

#716 Metricbeat daemonset deployment optional
  metricbeat/README.md
  metricbeat/templates/daemonset.yaml
  metricbeat/templates/deployment.yaml
  metricbeat/tests/metricbeat_test.py
  metricbeat/values.yaml
Labels: enhancement, metricbeat, v6.8.11, v7.8.1, v7.9.0

#387 Make kube-state-metrics optional for installation
  metricbeat/README.md
  metricbeat/requirements.lock
  metricbeat/requirements.yaml
  metricbeat/templates/deployment.yaml
  metricbeat/tests/metricbeat_test.py
  metricbeat/values.yaml
Labels: enhancement, metricbeat, v6.8.11, v7.8.1

#670 [elasticsearch] _helpers.tpl - elasticsearch.endpoints to use elasticsearch.uname
  elasticsearch/templates/_helpers.tpl
  elasticsearch/tests/elasticsearch_test.py
Labels: bug, elasticsearch

#724 [logstash] remove expected logstash host and name assertion
  logstash/examples/default/test/goss.yaml
  logstash/examples/elasticsearch/test/goss.yaml
  logstash/examples/oss/test/goss.yaml
  logstash/examples/security/test/goss.yaml
Labels: bug, logstash, v6.8.11

#723 [logstash] Restart the logstash pod when the secrets have changed
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
Labels: enhancement, logstash

#727 [elasticsearch] Update test image pull policy.
  elasticsearch/templates/test/test-elasticsearch-health.yaml
Labels: elasticsearch, enhancement

#726 [Kibana] Add loadbalancerIP to service spec in kibana
  kibana/templates/service.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: feature request, kibana, v6.8.11, v7.8.1

#728 [meta] use same staging job for all branches
  .ci/jobs/elastic+helm-charts+staging+cluster-cleanup.yml
  .ci/jobs/elastic+helm-charts+staging+cluster-creation.yml
  .ci/jobs/elastic+helm-charts+staging+integration-apm-server.yml
  .ci/jobs/elastic+helm-charts+staging+integration-elasticsearch.yml
  .ci/jobs/elastic+helm-charts+staging+integration-filebeat.yml
  .ci/jobs/elastic+helm-charts+staging+integration-kibana.yml
  .ci/jobs/elastic+helm-charts+staging+integration-logstash.yml
  .ci/jobs/elastic+helm-charts+staging+integration-metricbeat.yml
  .ci/jobs/elastic+helm-charts+staging.yml
Labels: meta

#735 [meta] use branch_specifier param instead of BRANCH
  .ci/jobs/elastic+helm-charts+staging+cluster-cleanup.yml
  .ci/jobs/elastic+helm-charts+staging+cluster-creation.yml
  .ci/jobs/elastic+helm-charts+staging+integration-apm-server.yml
  .ci/jobs/elastic+helm-charts+staging+integration-elasticsearch.yml
  .ci/jobs/elastic+helm-charts+staging+integration-filebeat.yml
  .ci/jobs/elastic+helm-charts+staging+integration-kibana.yml
  .ci/jobs/elastic+helm-charts+staging+integration-logstash.yml
  .ci/jobs/elastic+helm-charts+staging+integration-metricbeat.yml
  .ci/jobs/elastic+helm-charts+staging.yml
Labels: meta

#738 [meta] fix staging job
  .ci/jobs/elastic+helm-charts+staging.yml
Labels: bug, meta

#737 [doc] fix some links
  apm-server/README.md
  elasticsearch/README.md
  filebeat/README.md
  kibana/README.md
  logstash/README.md
  metricbeat/README.md
Labels: doc

#718 [meta] add slack notifications to CI jobs
  .ci/jobs/defaults.yml
  .ci/jobs/elastic+helm-charts+master.yml
  .ci/jobs/elastic+helm-charts+staging.yml
Labels: meta

#742 fixup! [meta] add slack notifications to CI jobs (#718)
  .ci/jobs/elastic+helm-charts+staging.yml
Labels: meta

#743 [meta] add slack token to ci jobs
  .ci/jobs/elastic+helm-charts+master.yml
  .ci/jobs/elastic+helm-charts+staging.yml
Labels: meta

#740 [elasticsearch] remove initial_master_nodes test
  elasticsearch/templates/_helpers.tpl
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
Labels: bug, v6.8.11

#739 [meta] allow concurrency for staging jobs
  .ci/jobs/elastic+helm-charts+staging+cluster-cleanup.yml
  .ci/jobs/elastic+helm-charts+staging+cluster-creation.yml
  .ci/jobs/elastic+helm-charts+staging+integration-apm-server.yml
  .ci/jobs/elastic+helm-charts+staging+integration-elasticsearch.yml
  .ci/jobs/elastic+helm-charts+staging+integration-filebeat.yml
  .ci/jobs/elastic+helm-charts+staging+integration-kibana.yml
  .ci/jobs/elastic+helm-charts+staging+integration-logstash.yml
  .ci/jobs/elastic+helm-charts+staging+integration-metricbeat.yml
Labels: meta

#741 [doc] fix typos
  CONTRIBUTING.md
Labels: doc

#751 [meta] add auth-token-credential-id entry for slack
  .ci/jobs/elastic+helm-charts+master.yml
  .ci/jobs/elastic+helm-charts+staging.yml
Labels: meta

#754 7.8.1 Release
  README.md
  apm-server/Chart.yaml
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  apm-server/values.yaml
  elasticsearch/Chart.yaml
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/default/test/goss.yaml
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/security/README.md
  elasticsearch/examples/upgrade/README.md
  elasticsearch/examples/upgrade/test/goss.yaml
  elasticsearch/values.yaml
  filebeat/Chart.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/examples/security/values.yaml
  filebeat/values.yaml
  helpers/bumper.py
  helpers/examples.mk
  kibana/Chart.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  kibana/values.yaml
  logstash/Chart.yaml
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/examples/security/README.md
  logstash/values.yaml
  metricbeat/Chart.yaml
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/values.yaml
Labels: meta, v7.8.1

#753 6.8.11 Release
  .ci/jobs.t/elastic+helm-charts+{branch}+staging.yml
  README.md
  apm-server/Chart.yaml
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  apm-server/values.yaml
  elasticsearch/Chart.yaml
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/security/README.md
  elasticsearch/values.yaml
  filebeat/Chart.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/values.yaml
  helpers/bumper.py
  helpers/examples.mk
  kibana/Chart.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  kibana/values.yaml
  logstash/Chart.yaml
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/values.yaml
  metricbeat/Chart.yaml
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/values.yaml
Labels: meta, v6.8.11

#755 [meta] update changelog for 7.8.1 and 6.8.11 releases
  BREAKING_CHANGES.md
  CHANGELOG.md
  README.md
  apm-server/README.md
  elasticsearch/README.md
  filebeat/README.md
  kibana/README.md
  logstash/README.md
  metricbeat/README.md
Labels: meta, v6.8.11, v7.8.1

#756 [release] Initiate 7.9 branch
  CONTRIBUTING.md
  README.md
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/migration/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/security/README.md
  elasticsearch/examples/upgrade/README.md
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/templates/daemonset.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/examples/security/README.md
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/templates/daemonset.yaml
Labels: meta, v7.9.0

#760 [meta] add slack notifications to CI jobs
  .ci/jobs.t/elastic+helm-charts+{branch}+staging.yml
  .ci/jobs.t/elastic+helm-charts+{branch}.yml
Labels: meta

#758 [doc] update doc links
  elasticsearch/README.md
  elasticsearch/examples/migration/README.md
  filebeat/README.md
Labels: doc

#759 [meta] add helm 3 beta support
  README.md
  apm-server/README.md
  elasticsearch/README.md
  filebeat/README.md
  kibana/README.md
  logstash/README.md
  metricbeat/README.md
Labels: meta, v7.9.0

#736 [meta] remove branch specific staging jobs
  .ci/jobs.t/elastic+helm-charts+{branch}+staging+cluster-cleanup.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+staging+cluster-creation.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+staging+integration-apm-server.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+staging+integration-elasticsearch.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+staging+integration-filebeat.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+staging+integration-kibana.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+staging+integration-logstash.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+staging+integration-metricbeat.yml
  .ci/jobs.t/elastic+helm-charts+{branch}+staging.yml
Labels: meta
