Repository elastic/helm-charts, pull requests merged in 2021-02, with the labels that each got.

#1040 fix: security.yaml is 404
  elasticsearch/examples/security/README.md
Labels: docs, elasticsearch, need-backport

#1039 [metricbeat] Fixing the respository of kube-state-metrics for metricbeats
  metricbeat/README.md
Labels: docs, metricbeat, need-backport

#883 [logstash] Add support to use pattern files
  logstash/README.md
  logstash/templates/configmap-pattern.yaml
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: feature, logstash

#1046 [elasticsearch][kibana] remove oss examples
  apm-server/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/oss/test/goss.yaml
  apm-server/examples/oss/values.yaml
  elasticsearch/README.md
  elasticsearch/examples/oss/Makefile
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/oss/values.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/examples/oss/test/goss.yaml
  filebeat/examples/oss/values.yaml
  helpers/matrix.yml
  kibana/README.md
  kibana/examples/oss/Makefile
  kibana/examples/oss/README.md
  kibana/examples/oss/test/goss.yaml
  kibana/examples/oss/values.yaml
  logstash/README.md
  metricbeat/README.md
  metricbeat/examples/oss/test/goss-metrics.yaml
  metricbeat/examples/oss/test/goss.yaml
  metricbeat/examples/oss/values.yaml
Labels: elasticsearch, kibana, meta, need-backport, v7.11.0

#1065 [meta] bump helm support to 3.5.2
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: meta, need-backport

#1052 [elasticsearch][kibana] remove oss examples (#1046)
  apm-server/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/oss/test/goss.yaml
  apm-server/examples/oss/values.yaml
  elasticsearch/README.md
  elasticsearch/examples/oss/Makefile
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/oss/values.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/examples/deployment/README.md
  filebeat/examples/oss/test/goss.yaml
  filebeat/examples/oss/values.yaml
  helpers/matrix.yml
  kibana/README.md
  kibana/examples/oss/Makefile
  kibana/examples/oss/README.md
  kibana/examples/oss/test/goss.yaml
  kibana/examples/oss/values.yaml
  logstash/README.md
  metricbeat/README.md
  metricbeat/examples/oss/test/goss-metrics.yaml
  metricbeat/examples/oss/test/goss.yaml
  metricbeat/examples/oss/values.yaml
Labels: elasticsearch, kibana, meta

#1053 [elasticsearch][kibana] remove oss examples (#1046)
  apm-server/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/oss/test/goss.yaml
  apm-server/examples/oss/values.yaml
  elasticsearch/README.md
  elasticsearch/examples/oss/Makefile
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/oss/test/goss.yaml
  elasticsearch/examples/oss/values.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/examples/deployment/README.md
  filebeat/examples/oss/test/goss.yaml
  filebeat/examples/oss/values.yaml
  helpers/matrix.yml
  kibana/README.md
  kibana/examples/oss/Makefile
  kibana/examples/oss/README.md
  kibana/examples/oss/test/goss.yaml
  kibana/examples/oss/values.yaml
  logstash/README.md
  metricbeat/README.md
  metricbeat/examples/oss/test/goss-metrics.yaml
  metricbeat/examples/oss/test/goss.yaml
  metricbeat/examples/oss/values.yaml
Labels: elasticsearch, kibana, meta

#1071 7.11.1 changelog
  BREAKING_CHANGES.md
  CHANGELOG.md
  README.md
Labels: meta

#1077 [6.8] [logstash] Add support to use pattern files (#883)
  logstash/README.md
  logstash/templates/configmap-pattern.yaml
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#1079 [7.x] [logstash] Add support to use pattern files (#883)
  logstash/README.md
  logstash/templates/configmap-pattern.yaml
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#1078 [7.11] [logstash] Add support to use pattern files (#883)
  logstash/README.md
  logstash/templates/configmap-pattern.yaml
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#952 [6.8] [meta] enable filebeat and metricbeat upgrade test
  filebeat/examples/upgrade/Makefile
  helpers/matrix.yml
Labels: backport, v6.8.15

#1080 [6.8] [meta] bump helm support to 3.5.2 (#1065)
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport

#1081 [7.11] [meta] bump helm support to 3.5.2 (#1065)
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport

#1082 [7.x] [meta] bump helm support to 3.5.2 (#1065)
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport
