Repository elastic/helm-charts, pull requests merged in 2021-04, with the labels that each got.

#1135 [elasticsearch] heap size is no longer defaulted to 1g
  elasticsearch/README.md
Labels: docs, elasticsearch, need-backport

#1141 [meta] add tests for k8s 1.18 and remove 1.15
  helpers/matrix.yml
  helpers/terraform/Makefile
Labels: meta

#1142 [6.8] [meta] add tests for k8s 1.18 and remove 1.15 (#1141)
  helpers/matrix.yml
  helpers/terraform/Makefile
Labels: backport

#1144 [7.x] [meta] add tests for k8s 1.18 and remove 1.15 (#1141)
  helpers/matrix.yml
  helpers/terraform/Makefile
Labels: backport

#1143 [7.12] [meta] add tests for k8s 1.18 and remove 1.15 (#1141)
  helpers/matrix.yml
  helpers/terraform/Makefile
Labels: backport

#1140 [meta] update PyYAML dependencies
  helpers/helm-tester/requirements.txt
  requirements.txt
Labels: meta, need-backport

#1145 [6.8] [meta] update PyYAML dependencies (#1140)
  helpers/helm-tester/requirements.txt
  requirements.txt
Labels: backport

#1146 [7.12] [meta] update PyYAML dependencies (#1140)
  helpers/helm-tester/requirements.txt
  requirements.txt
Labels: backport

#1147 [7.x] [meta] update PyYAML dependencies (#1140)
  helpers/helm-tester/requirements.txt
  requirements.txt
Labels: backport

#1157 [6.8] [elasticsearch] heap size is no longer defaulted to 1g (#1135)
  elasticsearch/README.md
Labels: backport

#1158 [7.12] [elasticsearch] heap size is no longer defaulted to 1g (#1135)
  elasticsearch/README.md
Labels: backport

#1159 [7.x] [elasticsearch] heap size is no longer defaulted to 1g (#1135)
  elasticsearch/README.md
Labels: backport

#1163 [6.8] [meta] update backport config for 7.12 branch (#1112)
  .backportrc.json
Labels: backport

#1164 [7.12] [meta] update backport config for 7.12 branch (#1112)
  .backportrc.json
Labels: backport

#1165 [7.x] [meta] update backport config for 7.12 branch (#1112)
  .backportrc.json
Labels: backport

#1166 [6.8] [elasticsearch] Mark esMajorVersion as deprecated (#1109)
  elasticsearch/README.md
Labels: backport

#1167 [7.12] [elasticsearch] Mark esMajorVersion as deprecated (#1109)
  elasticsearch/README.md
Labels: backport

#1168 [7.x] [elasticsearch] Mark esMajorVersion as deprecated (#1109)
  elasticsearch/README.md
Labels: backport

#1161 [7.12] [meta] add helm 3.5.3 support (#1128)
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport

#1162 [7.x] [meta] add helm 3.5.3 support (#1128)
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport

#1160 [6.8] [meta] add helm 3.5.3 support (#1128)
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport

#1169 [6.8] Bump py from 1.8.0 to 1.10.0 in /helpers/helm-tester (#1154)
  helpers/helm-tester/requirements.txt
Labels: backport

#1170 [7.12] Bump py from 1.8.0 to 1.10.0 in /helpers/helm-tester (#1154)
  helpers/helm-tester/requirements.txt
Labels: backport

#1172 [6.8] Bump py from 1.8.0 to 1.10.0 (#1155)
  requirements.txt
Labels: backport

#1173 [7.12] Bump py from 1.8.0 to 1.10.0 (#1155)
  requirements.txt
Labels: backport

#1174 [7.x] Bump py from 1.8.0 to 1.10.0 (#1155)
  requirements.txt
Labels: backport
