Repository elastic/helm-charts, pull requests merged in 2021-01, with the labels that each got.

#498 Add support for NetworkPolicy.
  elasticsearch/README.md
  elasticsearch/examples/networkpolicy/Makefile
  elasticsearch/examples/networkpolicy/values.yml
  elasticsearch/templates/networkpolicy.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: elasticsearch, feature

#1000 [logstash] disable privileged container in psp
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: enhancement, logstash, need-backport

#1004 Filebeat deployment support feature (#964)
  filebeat/README.md
  filebeat/examples/deployment/Makefile
  filebeat/examples/deployment/README.md
  filebeat/examples/deployment/test/goss.yaml
  filebeat/examples/deployment/values.yaml
  filebeat/templates/configmap.yaml
  filebeat/templates/daemonset.yaml
  filebeat/templates/deployment.yaml
  filebeat/tests/filebeat_test.py
  filebeat/values.yaml
  helpers/matrix.yml
Labels: backport

#1005 Filebeat deployment support feature (#964)
  filebeat/README.md
  filebeat/examples/deployment/Makefile
  filebeat/examples/deployment/README.md
  filebeat/examples/deployment/test/goss.yaml
  filebeat/examples/deployment/values.yaml
  filebeat/templates/configmap.yaml
  filebeat/templates/daemonset.yaml
  filebeat/templates/deployment.yaml
  filebeat/tests/filebeat_test.py
  filebeat/values.yaml
  helpers/matrix.yml
Labels: backport

#1006 [filebeat] Configurable ClusterRole (#978)
  filebeat/README.md
  filebeat/templates/clusterrole.yaml
  filebeat/values.yaml
Labels: backport

#1007 [filebeat] Configurable ClusterRole (#978)
  filebeat/README.md
  filebeat/templates/clusterrole.yaml
  filebeat/values.yaml
Labels: backport

#996 [apm-server] run as non root user
  apm-server/templates/deployment.yaml
  apm-server/tests/apmserver_test.py
  apm-server/values.yaml
Labels: apm-server, enhancement, need-backport

#1009 [filebeat][metricbeat] Update documentation on port collisions for multiple beats agents with hostNetworking enabled. (#997)
  filebeat/README.md
  metricbeat/README.md
Labels: backport

#1010 [filebeat][metricbeat] Update documentation on port collisions for multiple beats agents with hostNetworking enabled. (#997)
  filebeat/README.md
  metricbeat/README.md
Labels: backport

#1011 [filebeat][metricbeat] Update documentation on port collisions for multiple beats agents with hostNetworking enabled. (#997)
  filebeat/README.md
  metricbeat/README.md
Labels: backport

#1012 [elasticsearch] fix secrets in config example
  elasticsearch/examples/config/test/goss.yaml
  elasticsearch/examples/config/values.yaml
Labels: bug, elasticsearch, need-backport, v6.8.15, v7.11.0

#1016 [meta] Initiate 7.11 branch
  CONTRIBUTING.md
  README.md
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/migration/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/security/README.md
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/templates/daemonset.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/templates/daemonset.yaml
Labels: meta

#1017 NIT Update backport config and small doc fixes
  .backportrc.json
  README.md
  filebeat/README.md
Labels: meta

#1022 [meta] small fixes for 7.11 branch
  apm-server/README.md
  helpers/upgrade.sh
  kibana/examples/upgrade/Makefile
  kibana/examples/upgrade/test/goss.yaml
  metricbeat/examples/upgrade/test/goss-metrics.yaml
Labels: meta

#1018 [meta] fix transient errors with stable repository
  helpers/terraform/Makefile
  metricbeat/examples/default/Makefile
  metricbeat/examples/oss/Makefile
  metricbeat/examples/security/Makefile
  metricbeat/examples/upgrade/Makefile
Labels: meta

#1025 [meta] bump helm version to 3.5.0
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: meta, v6.8.14, v7.11.0

#1033 [meta] add build status and artifact hub badges
  README.md
  apm-server/README.md
  elasticsearch/README.md
  filebeat/README.md
  kibana/README.md
  logstash/README.md
  metricbeat/README.md
Labels: meta

#809 [filebeat] variable maxUnavailable updateStrategy
  filebeat/README.md
  filebeat/templates/daemonset.yaml
  filebeat/tests/filebeat_test.py
  filebeat/values.yaml
Labels: filebeat, need-backport, v6.8.14, v7.11.0
