Repository elastic/helm-charts, pull requests merged in 2021-09, with the labels that each got.

#1337 [meta] remove support matrix + nit doc changes
  README.md
Labels: meta, need-backport

#1350 [6.8] [meta] remove support matrix + nit doc changes (#1337)
  README.md
Labels: backport

#1352 [7.x] [meta] remove support matrix + nit doc changes (#1337)
  README.md
Labels: backport

#1351 [7.14] [meta] remove support matrix + nit doc changes (#1337)
  README.md
Labels: backport

#1338 [6.8] [elasticsearch] add value to disable service (#1115)
  elasticsearch/README.md
  elasticsearch/templates/service.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: backport

#1339 [7.14] [elasticsearch] add value to disable service (#1115)
  elasticsearch/README.md
  elasticsearch/templates/service.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: backport

#1340 [7.x] [elasticsearch] add value to disable service (#1115)
  elasticsearch/README.md
  elasticsearch/templates/service.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: backport

#1341 [6.8] [elasticsearch] add value to disable tests (#1116)
  elasticsearch/README.md
  elasticsearch/templates/NOTES.txt
  elasticsearch/templates/test/test-elasticsearch-health.yaml
  elasticsearch/values.yaml
Labels: backport

#1345 [7.14] [meta] add helm 3.6.2 support (#1232)
  README.md
  helpers/examples.mk
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport

#1343 [7.x] [elasticsearch] add value to disable tests (#1116)
  elasticsearch/README.md
  elasticsearch/templates/NOTES.txt
  elasticsearch/templates/test/test-elasticsearch-health.yaml
  elasticsearch/values.yaml
Labels: backport

#1342 [7.14] [elasticsearch] add value to disable tests (#1116)
  elasticsearch/README.md
  elasticsearch/templates/NOTES.txt
  elasticsearch/templates/test/test-elasticsearch-health.yaml
  elasticsearch/values.yaml
Labels: backport

#1346 [7.x] [meta] add helm 3.6.2 support (#1232)
  README.md
  helpers/examples.mk
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport

#1344 [6.8] [meta] add helm 3.6.2 support (#1232)
  README.md
  helpers/examples.mk
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport

#1347 [6.8] [meta] add tests for k8s 1.20 (#1294)
  helpers/matrix.yml
Labels: backport

#1348 [7.14] [meta] add tests for k8s 1.20 (#1294)
  helpers/matrix.yml
Labels: backport

#1349 [7.x] [meta] add tests for k8s 1.20 (#1294)
  helpers/matrix.yml
Labels: backport

#1362 [meta] remove contributing file from 6.8 branch
  CONTRIBUTING.md
Labels: meta

#1360 [meta] remove contributing file from 7.14 branch
  CONTRIBUTING.md
Labels: meta

#1361 [meta] remove contributing file from 7.15 branch
  CONTRIBUTING.md
Labels: meta

#1372 [7.15] [elasticsearch] Add namespace to helm test command in NOTES.txt (#1105)
  elasticsearch/templates/NOTES.txt
Labels: backport

#1366 [7.15] [elasticsearch] add value to disable service (#1115)
  elasticsearch/README.md
  elasticsearch/templates/service.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: backport

#1367 [7.15] [elasticsearch] add value to disable tests (#1116)
  elasticsearch/README.md
  elasticsearch/templates/NOTES.txt
  elasticsearch/templates/test/test-elasticsearch-health.yaml
  elasticsearch/values.yaml
Labels: backport

#1368 [7.15] [meta] add helm 3.6.2 support (#1232)
  README.md
  helpers/examples.mk
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: backport

#1369 [7.15] [meta] add tests for k8s 1.20 (#1294)
  helpers/matrix.yml
Labels: backport

#1377 7.15.0 release changelog
  CHANGELOG.md
  README.md
Labels: meta
