Repository elastic/helm-charts, pull requests merged in 2021-06, with the labels that each got.

#1215 [7.x] [elasticsearch] remove masterTerminationFix (#1183)
  elasticsearch/README.md
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: backport

#1214 [7.13] [elasticsearch] remove masterTerminationFix (#1183)
  elasticsearch/README.md
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: backport

#1216 [6.8] [elasticsearch] fix statefulset to rollout in upgrade test (#1189)
  elasticsearch/examples/upgrade/Makefile
Labels: backport

#1217 [7.13] [elasticsearch] fix statefulset to rollout in upgrade test (#1189)
  elasticsearch/examples/upgrade/Makefile
Labels: backport

#1218 [7.x] [elasticsearch] fix statefulset to rollout in upgrade test (#1189)
  elasticsearch/examples/upgrade/Makefile
Labels: backport

#1220 [7.13] [elasticsearch] remove unused sidecarResources value (#1185)
  elasticsearch/README.md
  elasticsearch/values.yaml
Labels: backport

#1221 [7.x] [elasticsearch] remove unused sidecarResources value (#1185)
  elasticsearch/README.md
  elasticsearch/values.yaml
Labels: backport

#1257 [logstash] feat: add podAffinity settings
  logstash/README.md
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: 7.13.3, enhancement, logstash, need-backport, v6.8.17

#1058 [elasticsearch] Added health pod name override for compatibility
  elasticsearch/README.md
  elasticsearch/templates/test/test-elasticsearch-health.yaml
  elasticsearch/values.yaml
Labels: 7.13.3, elasticsearch, enhancement, need-backport
