Repository elastic/helm-charts, pull requests merged in 2021-07, with the labels that each got.

#1270 [7.13] [meta] add tests for k8s 1.19 (#1231)
  helpers/matrix.yml
Labels: backport

#1264 [kibana] adding extra volumes and extra volume mounts (#557)
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: 7.13.3, enhancement, kibana, need-backport, v6.8.17

#1271 [7.x] [meta] add tests for k8s 1.19 (#1231)
  helpers/matrix.yml
Labels: backport

#1274 [7.x] [elasticsearch] Added health pod name override for compatability (#1058)
  elasticsearch/README.md
  elasticsearch/templates/test/test-elasticsearch-health.yaml
  elasticsearch/values.yaml
Labels: backport

#1273 [7.13] [elasticsearch] Added health pod name override for compatability (#1058)
  elasticsearch/README.md
  elasticsearch/templates/test/test-elasticsearch-health.yaml
  elasticsearch/values.yaml
Labels: backport

#1277 [7.x] [logstash] feat: add podAffinity settings (#1257)
  logstash/README.md
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#1276 [7.13] [logstash] feat: add podAffinity settings (#1257)
  logstash/README.md
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#1272 [6.8] [elasticsearch] Added health pod name override for compatability (#1058)
  elasticsearch/README.md
  elasticsearch/templates/test/test-elasticsearch-health.yaml
  elasticsearch/values.yaml
Labels: backport

#1275 [6.8] [logstash] feat: add podAffinity settings (#1257)
  logstash/README.md
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#1115 [elasticsearch] add value to disable service
  elasticsearch/README.md
  elasticsearch/templates/service.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: elasticsearch, enhancement

#1278 [6.8] [kibana] adding extra volumes and extra volume mounts (#557) (#1264)
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: backport

#1280 [7.x] [kibana] adding extra volumes and extra volume mounts (#557) (#1264)
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: backport

#1279 [7.13] [kibana] adding extra volumes and extra volume mounts (#557) (#1264)
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: backport

#1116 [elasticsearch] add value to disable tests
  elasticsearch/README.md
  elasticsearch/templates/NOTES.txt
  elasticsearch/templates/test/test-elasticsearch-health.yaml
  elasticsearch/values.yaml
Labels: elasticsearch, enhancement

#1232 [meta] add helm 3.6.2 support
  README.md
  helpers/examples.mk
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
Labels: meta, need-backport

#1286 [meta] remove gke 1.17 tests
  helpers/matrix.yml
  helpers/terraform/Dockerfile
  helpers/terraform/Makefile
Labels: meta, need-backport, v6.8.17, v7.13.3

#1288 [7.13] [meta] remove gke 1.17 tests (#1286)
  helpers/matrix.yml
  helpers/terraform/Dockerfile
  helpers/terraform/Makefile
Labels: backport

#1289 [7.x] [meta] remove gke 1.17 tests (#1286)
  helpers/matrix.yml
  helpers/terraform/Dockerfile
  helpers/terraform/Makefile
Labels: backport

#1287 [6.8] [meta] remove gke 1.17 tests (#1286)
  helpers/matrix.yml
  helpers/terraform/Dockerfile
  helpers/terraform/Makefile
Labels: backport

#1283 6.8.17 release
  README.md
  apm-server/Chart.yaml
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  apm-server/values.yaml
  elasticsearch/Chart.yaml
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/oss/README.md
  elasticsearch/examples/security/README.md
  elasticsearch/values.yaml
  filebeat/Chart.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/deployment/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/values.yaml
  helpers/examples.mk
  kibana/Chart.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/oss/README.md
  kibana/examples/security/README.md
  kibana/values.yaml
  logstash/Chart.yaml
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/values.yaml
  metricbeat/Chart.yaml
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/values.yaml
Labels: meta

#1294 [meta] add tests for k8s 1.20
  helpers/matrix.yml
Labels: meta, need-backport, v7.14.0

#1302 7.13.4 release
  apm-server/Chart.yaml
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  apm-server/values.yaml
  elasticsearch/Chart.yaml
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/default/test/goss.yaml
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/openshift/test/goss.yaml
  elasticsearch/examples/security/README.md
  elasticsearch/examples/upgrade/test/goss.yaml
  elasticsearch/values.yaml
  filebeat/Chart.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/deployment/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/values.yaml
  helpers/examples.mk
  kibana/Chart.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/security/README.md
  kibana/values.yaml
  logstash/Chart.yaml
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  logstash/values.yaml
  metricbeat/Chart.yaml
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/values.yaml
Labels: meta

#1305 [meta] update support matrix
  README.md
Labels: meta

#1306 [6.8] [meta] update support matrix (#1305)
  README.md
Labels: backport

#1307 [7.13] [meta] update support matrix (#1305)
  README.md
Labels: backport

#1308 [7.x] [meta] update support matrix (#1305)
  README.md
Labels: backport

#1269 [6.8] [meta] add tests for k8s 1.19 (#1231)
  filebeat/examples/security/values.yaml
  filebeat/values.yaml
  helpers/matrix.yml
Labels: backport
