Repository elastic/helm-charts, pull requests merged in 2021-12, with the labels that each got.

#1458 [elasticsearch] use bash for readiness script
  elasticsearch/templates/statefulset.yaml
Labels: bug, elasticsearch, v7.16.0

#1460 [meta] download goss outside of pods
  helpers/examples.mk
Labels: elasticsearch, v7.16.0

#1459 [7.x] [elasticsearch] use bash for readiness script (#1458)
  elasticsearch/templates/statefulset.yaml
Labels: backport

#1461 [7.x] [meta] download goss outside of pods (#1460)
  helpers/examples.mk
Labels: backport

#1464 [elasticsearch] use bash for keystore init container
  elasticsearch/templates/statefulset.yaml
Labels: elasticsearch, v7.16.1

#1466 [elasticsearch] fix a typo in 4e31e0cf3d025f9ce877ac52d218f49d72e26447
  elasticsearch/templates/statefulset.yaml
Labels: elasticsearch, v7.16.1

#1465 [7.x] [elasticsearch] use bash for keystore init container (#1464)
  elasticsearch/templates/statefulset.yaml
Labels: backport

#1470 [7.x] [metricbeat] remove es metricset search query for oss example (#1469)
  metricbeat/examples/oss/test/goss.yaml
Labels: backport

#1475 [meta] initiate 7.16 branch
  README.md
  apm-server/README.md
  apm-server/examples/default/README.md
  apm-server/examples/oss/README.md
  apm-server/examples/security/README.md
  elasticsearch/README.md
  elasticsearch/examples/config/README.md
  elasticsearch/examples/default/README.md
  elasticsearch/examples/docker-for-mac/README.md
  elasticsearch/examples/kubernetes-kind/README.md
  elasticsearch/examples/microk8s/README.md
  elasticsearch/examples/migration/README.md
  elasticsearch/examples/minikube/README.md
  elasticsearch/examples/multi/README.md
  elasticsearch/examples/openshift/README.md
  elasticsearch/examples/security/README.md
  elasticsearch/values.yaml
  filebeat/README.md
  filebeat/examples/default/README.md
  filebeat/examples/oss/README.md
  filebeat/examples/security/README.md
  filebeat/templates/daemonset.yaml
  kibana/README.md
  kibana/examples/default/README.md
  kibana/examples/openshift/README.md
  kibana/examples/security/README.md
  logstash/README.md
  logstash/examples/default/README.md
  logstash/examples/elasticsearch/README.md
  logstash/examples/oss/README.md
  metricbeat/README.md
  metricbeat/examples/default/README.md
  metricbeat/examples/oss/README.md
  metricbeat/examples/security/README.md
  metricbeat/templates/daemonset.yaml
Labels: meta

#1476 [meta] update backport config for 7.16 branch
  .backportrc.json
Labels: meta

#1477 [7.16] [meta] update backport config for 7.16 branch (#1476)
  .backportrc.json
Labels: backport

#1480 [elasticsearch] fix a lines order in example values
  elasticsearch/values.yaml
Labels: elasticsearch, need-backport

#1478 [7.16] [all] Add support to ingress networking.k8s.io/v1 & ingressClassName (#1409)
  apm-server/templates/ingress.yaml
  apm-server/values.yaml
  elasticsearch/templates/ingress.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
  kibana/templates/ingress.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
  logstash/templates/ingress.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#1479 [7.x] [all] Add support to ingress networking.k8s.io/v1 & ingressClassName (#1409)
  apm-server/templates/ingress.yaml
  apm-server/values.yaml
  elasticsearch/templates/ingress.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
  kibana/templates/ingress.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
  logstash/templates/ingress.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#1483 [7.16] [elasticsearch] fix a lines order in example values (#1480)
  elasticsearch/values.yaml
Labels: backport

#1484 [7.x] [elasticsearch] fix a lines order in example values (#1480)
  elasticsearch/values.yaml
Labels: backport

#1481 [kibana] optionally disable SA token automount (#1301)
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: backport

#1482 [kibana] optionally disable SA token automount (#1301)
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: backport

#1487 7.16.1 release changelog
  CHANGELOG.md
  README.md
Labels: meta

#1489 6.8.21 release changelog
  CHANGELOG.md
  README.md
Labels: meta

#1496 [elasticsearch] #1495 Configure JVM options files
  elasticsearch/README.md
  elasticsearch/templates/configmap.yaml
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: enhancement, elasticsearch

#1506 [elasticsearch] remove usage of ELASTIC_USERNAME
  elasticsearch/examples/config/test/goss.yaml
  elasticsearch/examples/config/values.yaml
  elasticsearch/examples/security/test/goss.yaml
  elasticsearch/examples/security/values.yaml
  elasticsearch/templates/statefulset.yaml
Labels: enhancement, elasticsearch, need-backport

#1507 [elasticsearch] remove usage of ELASTIC_USERNAME (#1506)
  elasticsearch/examples/config/test/goss.yaml
  elasticsearch/examples/config/values.yaml
  elasticsearch/examples/security/test/goss.yaml
  elasticsearch/examples/security/values.yaml
  elasticsearch/templates/statefulset.yaml
Labels: backport

#1508 [elasticsearch] remove usage of ELASTIC_USERNAME (#1506)
  elasticsearch/examples/config/test/goss.yaml
  elasticsearch/examples/config/values.yaml
  elasticsearch/examples/security/test/goss.yaml
  elasticsearch/examples/security/values.yaml
  elasticsearch/templates/statefulset.yaml
Labels: backport

#1503 [7.x] [elasticsearch] #1495 Configure JVM options files (#1496)
  elasticsearch/README.md
  elasticsearch/templates/configmap.yaml
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: backport

#1502 [7.16] [elasticsearch] #1495 Configure JVM options files (#1496)
  elasticsearch/README.md
  elasticsearch/templates/configmap.yaml
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: backport

#1501 [6.8] [elasticsearch] #1495 Configure JVM options files (#1496)
  elasticsearch/README.md
  elasticsearch/templates/configmap.yaml
  elasticsearch/templates/statefulset.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: backport

#1518 [meta] fix PR authors in changelog
  CHANGELOG.md
Labels: meta
