Repository elastic/helm-charts, pull requests merged in 2022-01, with the labels that each got.

#1522 [meta] fix yaml load warning in tests
  helpers/helpers.py
Labels: enhancement, meta, need-backport

#1530 [kibana] use bash for readiness script
  kibana/templates/deployment.yaml
Labels: bug, kibana, need-backport, v7.17.0

#1531 [7.x] [kibana] use bash for readiness script (#1530)
  kibana/templates/deployment.yaml
Labels: backport

#1533 [7.16] [tests] fix yaml load warning (#1522)
  helpers/helpers.py
Labels: backport

#1532 [6.8] [tests] fix yaml load warning (#1522)
  helpers/helpers.py
Labels: backport

#1534 [7.x] [tests] fix yaml load warning (#1522)
  helpers/helpers.py
Labels: backport

#1544 7.16.3 release changelog
  CHANGELOG.md
  README.md
Labels: meta
