Repository elastic/helm-charts, pull requests merged in 2022-03, with the labels that each got.

#1584 [7.17] fix(APM): add pod labels (#1527)
  apm-server/templates/deployment.yaml
Labels: backport

#1585 [7.17] [APM] fix podLabels (#1521)
  apm-server/tests/apmserver_test.py
Labels: backport

#1586 [7.17] [elasticsearch] add service.publishNotReadyAddresses parameter. (#1535)
  elasticsearch/README.md
  elasticsearch/templates/service.yaml
  elasticsearch/tests/elasticsearch_test.py
  elasticsearch/values.yaml
Labels: backport

#1587 [7.17] [elasticsearch] fix ServiceAccount inconsistencies (#1580)
  elasticsearch/templates/_helpers.tpl
  elasticsearch/templates/rolebinding.yaml
  elasticsearch/templates/serviceaccount.yaml
  elasticsearch/templates/statefulset.yaml
Labels: backport

#1588 [7.17] [logstash] fix ServiceAccount inconsistencies (#1581)
  logstash/templates/_helpers.tpl
  logstash/templates/rolebinding.yaml
  logstash/templates/serviceaccount.yaml
  logstash/templates/statefulset.yaml
Labels: backport

#1524 [metricbeat] bump kube-state-metrics to version 4.7.0
  helpers/helm-tester/Dockerfile
  metricbeat/README.md
  metricbeat/examples/default/Makefile
  metricbeat/examples/oss/Makefile
  metricbeat/examples/security/Makefile
  metricbeat/examples/upgrade/Makefile
  metricbeat/requirements.lock
  metricbeat/requirements.yaml
Labels: enhancement, metricbeat, need-backport, v7.17.0

#1590 [7.17] [elasticsearch][logstash] Add support to PodDisruptionBudget policy/v1 (#1420)
  elasticsearch/templates/poddisruptionbudget.yaml
  elasticsearch/templates/podsecuritypolicy.yaml
  logstash/templates/poddisruptionbudget.yaml
  logstash/templates/podsecuritypolicy.yaml
Labels: backport

#1589 [7.17] [meta] bump Helm version to 3.8.0 (#1563)
  README.md
  helpers/helm-tester/Dockerfile
  helpers/terraform/Dockerfile
  logstash/templates/poddisruptionbudget.yaml
Labels: backport

#1591 [7.17] [logstash] allow array values for extra (#1450)
  logstash/README.md
  logstash/templates/statefulset.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#1592 [7.17] [metricbeat] bump kube-state-metrics to version 4.7.0 (#1524)
  helpers/helm-tester/Dockerfile
  metricbeat/README.md
  metricbeat/examples/default/Makefile
  metricbeat/examples/oss/Makefile
  metricbeat/examples/security/Makefile
  metricbeat/examples/upgrade/Makefile
  metricbeat/requirements.lock
  metricbeat/requirements.yaml
Labels: breaking change, backport

#1570 [logstash] add externalTrafficPolicy support
  logstash/templates/service.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: logstash, need-backport, v7.17.0

#1582 [kibana] fix extra values default values
  kibana/README.md
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: kibana, need-backport, v7.17.0

#1595 [7.17] [logstash] add externalTrafficPolicy support (#1570)
  logstash/templates/service.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#1569 [logstash] add flexible ingress
  logstash/templates/ingress.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: logstash, need-backport, v7.17.0

#1593 [meta] add support for k8s 1.22
  helpers/matrix.yml
  helpers/terraform/Dockerfile
  helpers/terraform/Makefile
Labels: meta, need-backport, v7.17.0

#1597 [7.17] [logstash] add flexible ingress (#1569)
  logstash/templates/ingress.yaml
  logstash/tests/logstash_test.py
  logstash/values.yaml
Labels: backport

#1598 [7.17] [meta] add support for k8s 1.22 (#1593)
  helpers/matrix.yml
  helpers/terraform/Dockerfile
  helpers/terraform/Makefile
Labels: backport

#1417 Support to add Kibana annotations at deployment level
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: enhancement, kibana, need-backport, v7.17.0

#1599 [7.17] Support to add Kibana annotations at deployment level (#1417)
  kibana/README.md
  kibana/templates/deployment.yaml
  kibana/tests/kibana_test.py
  kibana/values.yaml
Labels: backport

#1600 [7.17] [metricbeat] Adding custerRole permissions for leader election (#1422)
  filebeat/templates/role.yaml
  metricbeat/templates/role.yaml
  metricbeat/values.yaml
Labels: backport

#1494 [elasticsearch] add keystore container securityContext
  elasticsearch/templates/statefulset.yaml
Labels: enhancement, elasticsearch, need-backport, v7.17.0

#1602 [filebeat] add missing rolebinding and cluster role rules
  filebeat/templates/rolebinding.yaml
  filebeat/values.yaml
Labels: enhancement, filebeat, need-backport, v7.17.0

#1601 [7.17] [elasticsearch] add keystore container securityContext (#1494)
  elasticsearch/templates/statefulset.yaml
Labels: backport

#1604 [meta] update docker images
  .ci/jobs/elastic+helm-charts+main+template-testing.yml
  .ci/jobs/elastic+helm-charts+pull-request+template-testing.yml
  CONTRIBUTING.md
  elasticsearch/tests/elasticsearch_test.py
  filebeat/tests/filebeat_test.py
  helpers/common.mk
  helpers/helm-tester/Dockerfile
  helpers/helm-tester/requirements.txt
  helpers/terraform/Dockerfile
  logstash/tests/logstash_test.py
  metricbeat/tests/metricbeat_test.py
  requirements.txt
Labels: meta, need-backport, v7.17.0

#1607 [7.17] [metricbeat] add missing rolebinding and cluster role rules (#1603)
  metricbeat/templates/rolebinding.yaml
  metricbeat/values.yaml
Labels: backport

#1608 [7.17] [meta] update docker images (#1604)
  .ci/jobs.t/elastic+helm-charts+{branch}+template-testing.yml
  elasticsearch/tests/elasticsearch_test.py
  filebeat/tests/filebeat_test.py
  helpers/common.mk
  helpers/helm-tester/Dockerfile
  helpers/helm-tester/requirements.txt
  helpers/terraform/Dockerfile
  logstash/tests/logstash_test.py
  metricbeat/tests/metricbeat_test.py
  requirements.txt
Labels: backport

#1606 [7.17] [filebeat] add missing rolebing and cluster role rules (#1602)
  filebeat/templates/rolebinding.yaml
  filebeat/values.yaml
Labels: backport

#1610 7.17.1 release changelog
  BREAKING_CHANGES.md
  CHANGELOG.md
  README.md
  apm-server/README.md
  elasticsearch/README.md
  filebeat/README.md
  kibana/README.md
  logstash/README.md
  metricbeat/README.md
Labels: meta

#1612 [metricbeat] fix upgrade test
  metricbeat/examples/upgrade/Makefile
Labels: meta, metricbeat, need-backport

#1622 [7.17] [metricbeat] fix upgrade test (#1612)
  metricbeat/examples/upgrade/Makefile
Labels: backport

#1624 [elasticsearch] fix certificate cnames
  elasticsearch/templates/_helpers.tpl
Labels: bug, elasticsearch

#1625 [elasticsearch] add subject dn to cert alternative names
  elasticsearch/templates/_helpers.tpl
Labels: bug, elasticsearch

#1629 [elasticsearch] upgrade test from 7.17.1 to 8.x
  elasticsearch/examples/upgrade/Makefile
Labels: meta, elasticsearch

#1628 [metricbeat] using https to connect to elasticsearch
  metricbeat/examples/default/test/goss-metrics.yaml
  metricbeat/examples/default/test/goss.yaml
  metricbeat/examples/oss/test/goss-metrics.yaml
  metricbeat/examples/oss/test/goss.yaml
  metricbeat/examples/oss/values.yaml
  metricbeat/examples/upgrade/test/goss-metrics.yaml
  metricbeat/examples/upgrade/test/goss.yaml
  metricbeat/examples/upgrade/values.yaml
  metricbeat/values.yaml
Labels: meta, metricbeat

#1631 [meta] update upgrade tests base version
  apm-server/examples/upgrade/Makefile
  filebeat/examples/upgrade/Makefile
Labels: meta, filebeat, apm-server, need-backport

#1632 [7.17] [meta] update upgrade tests base version (#1631)
  apm-server/examples/upgrade/Makefile
  filebeat/examples/upgrade/Makefile
Labels: backport

#1627 [filebeat] using https to connect to elasticsearch
  filebeat/examples/default/test/goss.yaml
  filebeat/examples/deployment/test/goss.yaml
  filebeat/examples/oss/test/goss.yaml
  filebeat/examples/oss/values.yaml
  filebeat/examples/upgrade/Makefile
  filebeat/examples/upgrade/test/goss.yaml
  filebeat/examples/upgrade/values.yaml
  filebeat/values.yaml
Labels: meta, filebeat
